<?php
$tally_config = array(
'site_logo' => 'none',
'site_logo_retina' => 'none',
'favicon' => '',
'preloader' => '',
'site_layout' => 'full',
'is_topbar' => 'no',
'is_header' => 'yes',
'is_subheader' => 'yes',
'sidebar_layout' => 'content-sidebar',
'enable_page_comment' => 'no',
'enable_post_comment' => 'yes',
'footer_widget_layout' => '3',
'footer_widget_1_column_width' => '',
'footer_widget_2_column_width' => '',
'footer_widget_3_column_width' => '',
'footer_widget_4_column_width' => '',
'footer_widget_5_column_width' => '',
'footer_widget_6_column_width' => '',
'footer_layout' => 'yes',
'enable_header_sticky' => 'no',
'header_height' => '',
'header_menu_top_margin' => '',
'header_logo_top_margin' => '',
'site_color_skin' => 'light',
'site_accent_color' => '#dd3333',
'site_accent2_color' => '#52a332',
'site_background' => '',
'color_headings_light' => '#ffffff',
'color_headings_dark' => '#444444',
'color_subheading_light' => '#e8e8e8',
'color_subheading_dark' => '#5e5e5e',
'color_text_light' => '#d3d3d3',
'color_text_dark' => '#777777',
'color_meta_light' => '#a3a3a3',
'color_meta_dark' => '#8e8e8e',
'color_border_light' => '#5e5e5e',
'color_border_dark' => '#c4c4c4',
'color_bg_light' => '#ffffff',
'color_bg_dark' => '#444444',
'color_inner_bg_light' => '#2d2d2d',
'color_inner_bg_dark' => '#f2f2f2',
'color_topbar_mood' => 'dark',
'color_topbar_bg' => array(
	'background-color' => '#f1f1f1',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'color_header_mood' => 'dark',
'color_header_bg' => array(
	'background-color' => '#ffffff',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'color_navigation_text' => '#444444',
'color_navigation_border' => '#444444',
'color_navigation_bg' => '#ffffff',
'color_navigation_text_hover' => '#E43131',
'color_navigation_border_hover' => '#E43131',
'color_navigation_bg_hover' => '#ffffff',
'color_navigation_submenu_bg' => '#f1f1f1',
'color_subheader_mood' => 'dark',
'color_subheader_bg' => array(
	'background-color' => '#f1f1f1',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'color_content_mood' => 'dark',
'color_content_bg' => array(
	'background-color' => '#ffffff',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'color_fwidget_mood' => 'light',
'color_fwidget_bg' => array(
	'background-color' => '#313131',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'color_footer_mood' => 'light',
'color_footer_bg' => array(
	'background-color' => '#1f1f1f',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'enable_google_fonts' => 'yes',
'headings_google_font_link' => '<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,700,400" rel="stylesheet" type="text/css" />',
'headings_google_font_family' => 'font-family: "Open Sans", sans-serif;',
'body_google_font_link' => '<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,700,400" rel="stylesheet" type="text/css" />',
'body_google_font_family' => 'font-family: "Open Sans", sans-serif;',
'h1_font_size' => '',
'h2_font_size' => '',
'h3_font_size' => '',
'h4_font_size' => '',
'h5_font_size' => '',
'h6_font_size' => '',
'body_font_size' => '',
'enable_social_icons' => 'yes',
'social_icons' => array(
	array(
		'title' => 'Dribbble',
		'link' => '#',
		'icon' => 'fa-dribbble',
	),
	array(
		'title' => 'Twitter',
		'link' => '#',
		'icon' => 'fa-twitter',
	),
	array(
		'title' => 'Facebook',
		'link' => '#',
		'icon' => 'fa-facebook',
	),
	array(
		'title' => 'Google Plus',
		'link' => '#',
		'icon' => 'fa-google-plus',
	),
),
'footer_copyright' => 'Copyright 2014 @ TallyThemes',
'custom_css' => '',
'custom_js' => '',
'google_analytics' => '',
'woocommerce_archive_page_porduct_column' => '3',
'woocommerce_cat_page_porduct_column' => '3',
'woocommerce_tag_page_porduct_column' => '3',
'woocommerce_related_porduct_column' => '4',
'ss1_top_padding' => '',
'ss1_bottom_padding' => '',
'ss1_bg' => '',
'ss2_top_padding' => '40px',
'ss2_bottom_padding' => '40px',
'ss2_bg' => array(
	'background-color' => '#5b5b5b',
	'background-repeat' => '',
	'background-attachment' => '',
	'background-position' => '',
	'background-size' => '',
	'background-image' => '',
),
'ss3_top_padding' => '',
'ss3_bottom_padding' => '',
'ss3_bg' => '',
'ss4_top_padding' => '',
'ss4_bottom_padding' => '',
'ss4_bg' => '',
'home_page_slideshow_enable' => 'on',
'home_page_slideshow_id' => '',
'home_page_accordion_enable' => 'on',
'home_page_accordion_title' => 'Home Accordion Contents',
'home_page_accordion_items' => array(
	array(
		'title' => 'Lorem ipsum dolor',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi.',
	),
	array(
		'title' => 'Suspendisse velit ante',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi.',
	),
	array(
		'title' => 'Praesent vel erat',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi.',
	),
	array(
		'title' => 'Nam vel tincidunt diam',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi.',
	),
),
'home_page_callout_enable' => 'on',
'home_page_callout_title' => 'Interactive Callout Section.',
'home_page_callout_button_text' => 'Read More',
'home_page_callout_button_link' => '#',
'home_page_callout_button_link_target' => '_self',
'home_page_callout_button_size' => '3x',
'home_page_callout_style' => 'center',
'home_page_callout_content' => 'Praesent vel erat malesuada, sodales risus ut, blandit sem. Ut quam velit, aliquam in bibendum eget, dapibus eu purus.',
'home_page_callout_class' => '',
'home_page_callout_content_width' => '',
'home_page_map_enable' => 'on',
'home_page_map_title' => 'Google Map',
'home_page_map_address' => 'Gold ST, New York, USA',
'home_page_map_type' => 'ROADMAP',
'home_page_map_width' => '100%',
'home_page_map_height' => '300px',
'home_page_map_zoom' => '15',
'home_page_map_scrollwheel' => 'true',
'home_page_map_scale' => 'true',
'home_page_map_popup' => 'true',
'home_page_map_zoom_pancontrol' => 'true',
'home_page_map_icon' => '',
'home_page_video_enable' => 'on',
'home_page_video_title' => 'Official Video of the site',
'home_page_video_html5' => 'no',
'home_page_video_src' => 'https://www.youtube.com/watch?v=_YbVJoMYwJ0',
'home_page_video_w' => '',
'home_page_video_h' => '',
'home_page_video_poster' => '',
'home_page_video_class' => '',
'home_page_blog_grid_enable' => 'on',
'home_page_blog_grid_title' => 'Blog UpdUate',
'home_page_blog_grid_category' => '',
'home_page_blog_grid_tags' => '',
'home_page_blog_grid_relation' => 'AND',
'home_page_blog_grid_limit' => '4',
'home_page_blog_grid_columns' => '4',
'home_page_blog_grid_orderby' => 'post_date',
'home_page_blog_grid_order' => 'DESC',
'home_page_blog_grid_filter' => 'yes',
'home_page_blog_grid_pagination' => 'yes',
'home_page_blog_grid_margin' => '3',
'home_page_blog_grid_animation_type' => '',
'home_page_blog_grid_animation_duration' => '',
'home_page_toggle_enable' => 'on',
'home_page_toggle_title' => 'Toggle Content is here.',
'home_page_toggle_items' => array(
	array(
		'title' => 'Lorem ipsum dolor',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.',
	),
	array(
		'title' => ' Nam vel tincidunt',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.',
	),
	array(
		'title' => 'Praesent vel erat',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.',
	),
	array(
		'title' => ' Quisque porttitor',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat.',
	),
),
'home_page_tab_enable' => 'on',
'home_page_tab_title' => 'Home Tab Contents',
'home_page_tab_items' => array(
	array(
		'title' => 'Tab 1',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi. Curabitur elit lacus, cursus at nunc sit amet, rutrum molestie odio. ',
	),
	array(
		'title' => 'Tab Two',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi. Curabitur elit lacus, cursus at nunc sit amet, rutrum molestie odio. ',
	),
	array(
		'title' => 'Tab 3',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi. Curabitur elit lacus, cursus at nunc sit amet, rutrum molestie odio. ',
	),
),
'home_page_text_enable' => 'on',
'home_page_text_title' => 'Well Come Text',
'home_page_text_content' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum. Nunc vehicula arcu adipiscing tempus eleifend. Etiam suscipit lectus ac dui venenatis placerat. Nulla facilisi. Curabitur elit lacus, cursus at nunc sit amet, rutrum molestie odio. Duis convallis mattis mi quis eleifend. Curabitur commodo libero augue, ac posuere augue volutpat vitae. Pellentesque ac nulla ipsum. Nunc vitae elit felis. Praesent tristique tellus diam.</p>
<p>Nam vel tincidunt diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent in tempus nisi. Sed congue lacinia turpis ut ullamcorper. Aliquam sagittis lobortis elementum. Mauris ornare ullamcorper sagittis. Duis facilisis dapibus tortor, ac sollicitudin ipsum venenatis in. Etiam aliquet, urna eget egestas iaculis, sapien lacus tincidunt magna, quis euismod arcu mi non odio. Morbi sed consequat libero. In rhoncus volutpat mauris convallis varius.</p>',
'home_page_textblock_enable' => 'on',
'home_page_textblock_title' => 'Home Text Blocks',
'home_page_textblock_column' => '4',
'home_page_textblock_items' => array(
	array(
		'title' => 'Nam vel tincidunt',
		'image' => '',
		'icon' => 'fa-adn',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'link' => '#',
		'readmore_text' => 'Read More',
	),
	array(
		'title' => 'Suspendisse velit',
		'image' => '',
		'icon' => 'fa-ambulance',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'link' => '#',
		'readmore_text' => 'Read More',
	),
	array(
		'title' => 'Quisque porttitor',
		'image' => '',
		'icon' => 'fa-anchor',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'link' => '#',
		'readmore_text' => 'Read More',
	),
	array(
		'title' => 'Nulla facilisi',
		'image' => '',
		'icon' => 'fa-automobile',
		'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius neque. Mauris egestas tellus eu libero viverra, quis faucibus nisi bibendum.',
		'link' => '#',
		'readmore_text' => 'Read More',
	),
),
'home_page_testimonial_slideshow_enable' => 'on',
'home_page_testimonial_slideshow_title' => 'Client Testimonials',
'home_page_testimonial_slideshow_category' => '',
'home_page_testimonial_slideshow_relation' => 'AND',
'home_page_testimonial_slideshow_limit' => '',
'home_page_testimonial_slideshow_orderby' => 'post_date',
'home_page_testimonial_slideshow_order' => 'DESC',
'home_page_testimonial_slideshow_animation' => 'slide',
'home_page_testimonial_slideshow_direction' => 'horizontal',
'home_page_testimonial_slideshow_smooth_height' => 'false',
'home_page_testimonial_slideshow_slideshow' => 'true',
'home_page_testimonial_slideshow_animation_loop' => 'true',
'home_page_testimonial_slideshow_slideshow_speed' => '7000',
'home_page_testimonial_slideshow_animation_speed' => '600',
'home_page_testimonial_slideshow_control_nav' => 'true',
'home_page_testimonial_slideshow_direction_nav' => 'true',
'home_page_testimonial_grid_enable' => 'on',
'home_page_testimonial_grid_title' => 'Client Testimonials',
'home_page_testimonial_grid_columns' => '3',
'home_page_testimonial_grid_margin' => '3',
'home_page_testimonial_grid_filter' => 'yes',
'home_page_testimonial_grid_category' => '',
'home_page_testimonial_grid_relation' => 'AND',
'home_page_testimonial_grid_limit' => '',
'home_page_testimonial_grid_orderby' => 'post_date',
'home_page_testimonial_grid_order' => 'DESC',
'home_page_testimonial_grid_pagination' => 'yes',
'home_page_testimonial_carousel_enable' => 'on',
'home_page_testimonial_carousel_title' => 'Client Testimonials',
'home_page_testimonial_carousel_category' => '',
'home_page_testimonial_carousel_relation' => 'AND',
'home_page_testimonial_carousel_limit' => '',
'home_page_testimonial_carousel_orderby' => 'post_date',
'home_page_testimonial_carousel_order' => 'DESC',
'home_page_testimonial_carousel_direction' => 'horizontal',
'home_page_testimonial_carousel_control_nav' => 'true',
'home_page_testimonial_carousel_direction_nav' => 'true',
'home_page_testimonial_carousel_item_width' => '100',
'home_page_testimonial_carousel_item_margin' => '10',
'home_page_testimonial_carousel_min_items' => '2',
'home_page_testimonial_carousel_max_items' => '4',
'home_page_testimonial_carousel_move' => '0',
'home_page_portfolio_slideshow_enable' => 'on',
'home_page_portfolio_slideshow_title' => 'Our Portfolio',
'home_page_portfolio_slideshow_category' => '',
'home_page_portfolio_slideshow_tag' => '',
'home_page_portfolio_slideshow_relation' => 'AND',
'home_page_portfolio_slideshow_limit' => '',
'home_page_portfolio_slideshow_orderby' => 'post_date',
'home_page_portfolio_slideshow_order' => 'DESC',
'home_page_portfolio_slideshow_animation' => 'slide',
'home_page_portfolio_slideshow_direction' => 'horizontal',
'home_page_portfolio_slideshow_smooth_height' => 'false',
'home_page_portfolio_slideshow_slideshow' => 'true',
'home_page_portfolio_slideshow_animation_loop' => 'true',
'home_page_portfolio_slideshow_slideshow_speed' => '7000',
'home_page_portfolio_slideshow_animation_speed' => '600',
'home_page_portfolio_slideshow_control_nav' => 'true',
'home_page_portfolio_slideshow_direction_nav' => 'true',
'home_page_portfolio_grid_enable' => 'on',
'home_page_portfolio_grid_title' => 'Our Projects',
'home_page_portfolio_grid_columns' => '4',
'home_page_portfolio_grid_margin' => '3',
'home_page_portfolio_grid_filter' => 'yes',
'home_page_portfolio_grid_category' => '',
'home_page_portfolio_grid_tag' => '',
'home_page_portfolio_grid_relation' => 'AND',
'home_page_portfolio_grid_limit' => '',
'home_page_portfolio_grid_orderby' => 'post_date',
'home_page_portfolio_grid_order' => 'DESC',
'home_page_portfolio_grid_pagination' => 'yes',
'home_page_portfolio_carousel_enable' => 'on',
'home_page_portfolio_carousel_title' => 'Our Work',
'home_page_portfolio_carousel_category' => '',
'home_page_portfolio_carousel_tag' => '',
'home_page_portfolio_carousel_relation' => 'AND',
'home_page_portfolio_carousel_limit' => '',
'home_page_portfolio_carousel_orderby' => 'post_date',
'home_page_portfolio_carousel_order' => 'DESC',
'home_page_portfolio_carousel_direction' => 'horizontal',
'home_page_portfolio_carousel_control_nav' => 'true',
'home_page_portfolio_carousel_direction_nav' => 'true',
'home_page_portfolio_carousel_item_width' => '100',
'home_page_portfolio_carousel_item_margin' => '10',
'home_page_portfolio_carousel_min_items' => '2',
'home_page_portfolio_carousel_max_items' => '4',
'home_page_portfolio_carousel_move' => '0',
'home_page_people_carousel_enable' => 'on',
'home_page_people_carousel_title' => 'Our Team Members',
'home_page_people_carousel_category' => '',
'home_page_people_carousel_relation' => 'AND',
'home_page_people_carousel_limit' => '',
'home_page_people_carousel_orderby' => 'post_date',
'home_page_people_carousel_order' => 'DESC',
'home_page_people_carousel_direction' => 'horizontal',
'home_page_people_carousel_control_nav' => 'true',
'home_page_people_carousel_direction_nav' => 'true',
'home_page_people_carousel_item_width' => '100',
'home_page_people_carousel_item_margin' => '10',
'home_page_people_carousel_min_items' => '2',
'home_page_people_carousel_max_items' => '4',
'home_page_people_carousel_move' => '0',
'home_page_people_grid_enable' => 'on',
'home_page_people_grid_title' => 'Our Team',
'home_page_people_grid_columns' => '4',
'home_page_people_grid_margin' => '3',
'home_page_people_grid_filter' => 'yes',
'home_page_people_grid_category' => '',
'home_page_people_grid_relation' => 'AND',
'home_page_people_grid_limit' => '',
'home_page_people_grid_orderby' => 'post_date',
'home_page_people_grid_order' => 'DESC',
'home_page_people_grid_pagination' => 'yes',
'home_page_people_slideshow_enable' => 'on',
'home_page_people_slideshow_title' => 'Our Team Members',
'home_page_people_slideshow_category' => '',
'home_page_people_slideshow_relation' => 'AND',
'home_page_people_slideshow_limit' => '',
'home_page_people_slideshow_orderby' => 'post_date',
'home_page_people_slideshow_order' => 'DESC',
'home_page_people_slideshow_animation' => 'slide',
'home_page_people_slideshow_direction' => 'horizontal',
'home_page_people_slideshow_smooth_height' => 'false',
'home_page_people_slideshow_slideshow' => 'true',
'home_page_people_slideshow_animation_loop' => 'true',
'home_page_people_slideshow_slideshow_speed' => '7000',
'home_page_people_slideshow_animation_speed' => '600',
'home_page_people_slideshow_control_nav' => 'true',
'home_page_people_slideshow_direction_nav' => 'true',
'home_page_logo_grid_enable' => 'on',
'home_page_logo_grid_title' => 'Our Sponsors ',
'home_page_logo_grid_columns' => '4',
'home_page_logo_grid_margin' => '3',
'home_page_logo_grid_filter' => 'yes',
'home_page_logo_grid_category' => '',
'home_page_logo_grid_relation' => 'AND',
'home_page_logo_grid_limit' => '',
'home_page_logo_grid_orderby' => 'post_date',
'home_page_logo_grid_order' => 'DESC',
'home_page_logo_grid_pagination' => 'yes',
'home_page_logo_slideshow_enable' => 'on',
'home_page_logo_slideshow_title' => 'Our Clients',
'home_page_logo_slideshow_category' => '',
'home_page_logo_slideshow_relation' => 'AND',
'home_page_logo_slideshow_limit' => '',
'home_page_logo_slideshow_orderby' => 'post_date',
'home_page_logo_slideshow_order' => 'DESC',
'home_page_logo_slideshow_animation' => 'slide',
'home_page_logo_slideshow_direction' => 'horizontal',
'home_page_logo_slideshow_smooth_height' => 'false',
'home_page_logo_slideshow_slideshow' => 'true',
'home_page_logo_slideshow_animation_loop' => 'true',
'home_page_logo_slideshow_slideshow_speed' => '7000',
'home_page_logo_slideshow_animation_speed' => '600',
'home_page_logo_slideshow_control_nav' => 'true',
'home_page_logo_slideshow_direction_nav' => 'true',
'home_page_logo_carousel_enable' => 'on',
'home_page_logo_carousel_title' => 'Our Sponsors ',
'home_page_logo_carousel_category' => '',
'home_page_logo_carousel_relation' => 'AND',
'home_page_logo_carousel_limit' => '',
'home_page_logo_carousel_orderby' => 'post_date',
'home_page_logo_carousel_order' => 'DESC',
'home_page_logo_carousel_direction' => 'horizontal',
'home_page_logo_carousel_control_nav' => 'true',
'home_page_logo_carousel_direction_nav' => 'true',
'home_page_logo_carousel_item_width' => '100',
'home_page_logo_carousel_item_margin' => '10',
'home_page_logo_carousel_min_items' => '2',
'home_page_logo_carousel_max_items' => '4',
'home_page_logo_carousel_move' => '0',
'home_page_audio_enable' => 'on',
'home_page_audio_title' => 'SoundCloud Audio',
'home_page_audio_html5' => 'no',
'home_page_audio_src' => 'https://soundcloud.com/zedsdead/zeds-dead-twin-shadow-lost-you-feat-dangelo-lacy',
'home_page_audio_w' => '',
'home_page_audio_h' => '',
'home_page_audio_poster' => '',
'home_page_audio_class' => '',
'home_page_gallery_single_enable' => 'on',
'home_page_gallery_single_title' => 'Gallery Single',
'home_page_gallery_single_slug' => '3254',
'home_page_gallery_single_columns' => '3',
'home_page_gallery_single_margin' => '1',
'home_page_gallery_archive_enable' => 'on',
'home_page_gallery_archive_title' => 'Gallery Album',
'home_page_gallery_archive_columns' => '3',
'home_page_gallery_archive_margin' => '3',
'home_page_gallery_archive_filter' => 'no',
'home_page_gallery_archive_category' => '',
'home_page_gallery_archive_relation' => 'AND',
'home_page_gallery_archive_limit' => '9',
'home_page_gallery_archive_orderby' => 'post_date',
'home_page_gallery_archive_order' => 'DESC',
'home_page_gallery_archive_pagination' => 'yes',
);